apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: first-applicatioin
  name: nginx-service
spec:
  ports:
    - name: name-of-service-port
      port: 80
      protocol: TCP
      targetPort: http-web-svc
  selector:
    app: nginx

